services:
  promise:
    image: leesw0924/promise
    platform: linux/amd64
    ports:
      - "80:8080"
    depends_on: []
    networks:
      - promise-network
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/home/ubuntu/promise/promise-435018-10ecba9c1524.json
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - /home/ubuntu/promise/promise-435018-10ecba9c1524.json:/home/ubuntu/promise/promise-435018-10ecba9c1524.json
      - /etc/localtime:/etc/localtime:ro
      - /usr/share/zoneinfo/Asia/Seoul:/etc/timezone:ro
networks:
  promise-network:
    driver: bridge