name: CI/CD for promise


on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Create application.yml from secrets
      run: echo "${{ secrets.PROMISE_APPLICATION_YML }}" > ./SpringBoot/src/main/resources/application.yml

    - name: Build with Gradle
      run: ./gradlew clean build
      working-directory: ./SpringBoot

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build and push promise image
      run: |
        docker build -t leesw0924/promise ./SpringBoot/
        docker push leesw0924/promise

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: SSH to EC2 and Deploy
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.PROMISE_EC2_HOST }}
        username: ${{ secrets.PROMISE_EC2_USERNAME }}
        key: ${{ secrets.PROMISE_EC2_PRIVATE_KEY }}
        script: |
          cd /home/ubuntu/promise
          docker compose down
          docker compose pull
          docker compose up -d